package hermes

import (
	"fmt"
	"os"
	"path/filepath"
)

const (
	// WrapperScriptName is the name of the wrapper script that Warren writes to shared-bin
	WrapperScriptName = "warren-hermes-wrapper.sh"
	// SharedBinMountPath is where the shared-bin volume is mounted in containers
	SharedBinMountPath = "/usr/local/shared-bin"
)

// WrapperScript generates the shell script that starts the Hermes watcher in background
// then execs the original command.
func WrapperScript() string {
	return `#!/bin/sh
# Warren Hermes Wrapper - auto-generated by Warren
# Starts Hermes watcher in background, then execs the original command

set -e

# Start Hermes watcher in background if hermes-watcher.sh exists
if [ -f /usr/local/shared-bin/hermes-watcher.sh ]; then
    echo "[warren-wrapper] Starting Hermes watcher in background..."
    /usr/local/shared-bin/hermes-watcher.sh &
else
    echo "[warren-wrapper] Warning: hermes-watcher.sh not found in shared-bin"
fi

# Exec the original command
echo "[warren-wrapper] Executing original command: $@"
exec "$@"
`
}

// WriteWrapperScript writes the Hermes wrapper script to the shared-bin directory.
// This should be called during Warren startup to ensure the script is available
// for injection into agent containers.
func WriteWrapperScript(sharedBinPath string) error {
	scriptPath := filepath.Join(sharedBinPath, WrapperScriptName)
	
	// Create the script content
	content := WrapperScript()
	
	// Write the script file
	if err := os.WriteFile(scriptPath, []byte(content), 0755); err != nil {
		return fmt.Errorf("failed to write wrapper script to %s: %w", scriptPath, err)
	}
	
	return nil
}

// WrapperCommand returns the command array that should be used to override
// the service command to use the Hermes wrapper.
func WrapperCommand(originalCommand []string) []string {
	wrapperPath := filepath.Join(SharedBinMountPath, WrapperScriptName)
	
	// Build the new command: ["/bin/sh", "/usr/local/shared-bin/warren-hermes-wrapper.sh", original_command...]
	cmd := []string{"/bin/sh", wrapperPath}
	cmd = append(cmd, originalCommand...)
	
	return cmd
}
